### ISSUE TITLE
Destination path already exists and is not an empty directory

### ISSUE THREAD

**Issue by ghost** [josip/eerie#1]
I'm trying to install Generys via Eerie and faced with following error.

<pre>$ eerie Generys git://github.com/josip/generys.git
 - Using base env.
 - Installing 'Generys' from git://github.com/josip/generys.git...
 > git clone git://github.com/josip/generys.git /home/kane/.eerie/env/base/addons/Generys
 ! Last command exited with the following error:

fatal: destination path '~/.eerie/env/base/addons/Generys' already exists and is not an empty directory.</pre>

Directory ~/.eerie/env/base/addons/Generys does not exist

**Comment by josip** [comment]
Updated readme. Fixes downloading Git projects. Closed by 07782e664d3ad87c1630f12eb87fdc47a302370a
